### ISSUE TITLE
Best place to add code that will act as "callbacks"?

### ISSUE THREAD

**Issue by Bpoole908** [AGI-Labs/continual_rl#5]
I'm interested in extending `continual_rl` by implementing some of my group's own continual RL algorithm ideas. However, there has been some incompatibilities from what I can see so far. I was wondering if anyone had any advice on some of these issues. In particular, I'm interested in running code related to the policy once a task completes (i.e., code that would normally be put inside the policy class). As I mentioned, from what I can tell, there doesn't seem to be a great way of doing this so I figured I'd ask a few questions before proceeding.

First, are there any recommended ways of doing this from the policy side without editing any source code? Meaning, solely from my own custom policy class which inherits from `PolicyBase`.

Second, would editing the experiment and policy base classes be a reasonable method for approaching this. Essentially, I'd add "callbacks" to the experiment loop that call methods from the policy before a cycle, after a cycle, before a task, and after a task. This is currently the approach I'm learning towards.

If you have any other suggestions or questions feel free to let me know.

**Comment by SamNPowers** [comment]
In general we discourage having task-specific things, since the direction we prefer is for the whole process to be task-agnostic. That said, we also want this repo to be as useful as possible for as many use cases as possible.

If I'm understanding you correctly, the easiest way to achieve what you want is to look at the task_id, and see if it has changed. We do something like this in progress_and_compress_monobeast.py, compute_loss, to determine when to reset the active column.

If this works for you, this method would be preferred over more callbacks that encourage task-boundary-based logic. Let me know if this won't work, however.

**Comment by Bpoole908** [comment]
> In general we discourage having task-specific things, since the direction we prefer is for the whole process to be task-agnostic. 

The current idea is task invariant but requires some extra computation that conveniently fits when transitioning between two tasks (one could think of this as the naive implementation). Theoretically, computing every so many time-steps, similar to how normal RL network training is done, could work too, but I want to try that later down the road.

> If I'm understanding you correctly, the easiest way to achieve what you want is to look at the task_id, and see if it has changed. 

I didn't think about the `task_id`, that could possibly work. The only place we have access to the `task_id` inside the policy is in the `compute_action()` method, correct?

> We do something like this in progress_and_compress_monobeast.py, compute_loss, to determine when to reset the active column.

I'll have to take a closer look at this code and see if I can find what you are referring to.

**Comment by SamNPowers** [comment]
Yeah, right now the task_spec is passed into the environment_runner, which, if you're using the batch or sync runners, just passes the task_id into compute_action. (The impala_environment_runner is kind of special, for various reasons...but that doesn't seem relevant here.)

I'm not necessarily averse to passing the task_id into train() as well, if it is sufficiently useful (again, I have my task-specific code hesitations but...practicality). 

Let me know if you have further questions, about progress and compress or anything else.

(Depending on what you're doing, writing your own environment runner might be a good solution as well, if you want more control over how collecting data and training are intertwined.)

**Comment by Bpoole908** [comment]
I think for now, using the `task_id` within the `compute_action()` method will suffice. I can simply check for when the `task_id` has changed to know we have moved onto a new task. Conceptually, one can think of the computation I'm trying to do similar to how  evaluation is ran after a task. I simply need to know if a task has ended, nothing else about it. Likewise, eventually, this can be done in a more continual manner, based on total time-steps or something else.

With that, this issue has roughly been resolved. I appreciate all the help! Does this package have a slack channel or some other forum where more basic questions can be asked? If not, I assume opening issues regarding questions is preferred then?

**Comment by SamNPowers** [comment]
A slack or discord channel is a good idea. I'll set one up over the weekend (probably discord as that's my preferred, but I'll consider). I'll post here and update the README once it's created. I'll close this afterwards.

But posting issues is also fine.

**Comment by Bpoole908** [comment]
I'll keep an eye out for the link! If it matters at all, I too would support the discord server idea.

**Comment by SamNPowers** [comment]
Discord created: https://discord.gg/VcNpAspbPm

I'll add it to the README after I've fleshed it out a touch more.
